[profile.default]
libs = ["lib"]
optimizer = true
optimizer_runs = 200
out = "out"
solc_version = "0.8.17"
src = "src"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
